---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


$log(\mathbb{E}[death_i]) = f(time_i) + \beta_1 pm10median_i + \beta_1 pm10median_i + \beta_2 so2median_i + \beta_3 o3median_i \beta_4 tmpd_i$



```{r}
library(mgcv)
library(gamair)
data(chicago)

model1 <- gam(death ~ s(time,bs="cr",k=200) + pm10median + 
             so2median + o3median + tmpd, data=chicago, family=poisson)


gam.check(model1)
```


```{r}
par(mfrow=c(2,1))
plot(model1,n=1000) # n increased to make plot smooth
plot(model1,residuals=TRUE,n=1000)
```

```{r}
plot(x=chicago$time, y=chicago$tmpd, type='l')
plot(x=chicago$time, y=chicago$o3median, type='l')

subset<-chicago[3000:3250,]

plot(x=subset$time, y=subset$death, type='l', xlab="time", ylab="death")
plot(x=subset$time, y=subset$tmpd, type='l', xlab="time", ylab="temp")
plot(x=subset$time, y=subset$o3median, type='l', xlab="time", ylab="ozone")

```


```{r}
chicago[is.na(chicago)]<-0
ap1<-gam(death~s(time,bs="cr",k=200)+s(pm10median,bs="cr")+s(so2median,bs="cr")+s(o3median,bs="cr")+s(tmpd,bs="cr"),data=chicago,family=poisson)

gam.check(ap1)
```

```{r}
lag.sum <- function(a,l0,l1)
## l0 is the smallest lag, l1 the largest
{ 
  n<-length(a)
  b<-rep(0,n-l1)
  for (i in 0:(l1-l0)) b <- b + a[(i+1):(n-l1+i)]
  b
}

death <- chicago$death[4:5114]
time <- chicago$time[4:5114]
o3ave <- lag.sum(chicago$o3median,0,3)
tmpave <- lag.sum(chicago$tmpd,0,3)
pm10ave <- lag.sum(log(chicago$pm10median+40),0,3)
so2 <- lag.sum(log(chicago$so2median+10),0,3)
```


```{r}

model2 <- gam(death ~ s(time, bs="cr", k=200) + te(o3ave, tmpave, k=8) + 
             s(pm10ave, bs="cr", k=6), family = poisson)


gam.check(model2)

plot(model2,n=1000) # n increased to make plot smooth

```

