---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(plyr)
library(dplyr)

require(utils)
library(zoo)
library(mgcv)

```



```{r}
trimspaces <- function(dat) {
  dat$COLUPC<-trimws(dat$COLUPC)
  dat$WEEK<-trimws(dat$WEEK)
  dat$IRI_KEY<-trimws(dat$IRI_KEY)
  return (dat)
}

combineupc <- function(dat) {
  dat$COLUPC<-paste(sprintf("%02d", dat$SY), dat$GE, sprintf("%05d", dat$VEND), sprintf("%05d", dat$ITEM), sep="")
  return (dat)
}
```



```{r}
panel.dk = read.table("data/toothpa_PANEL_DR_1427_1478.DAT", sep="", header = TRUE, na.strings="", stringsAsFactors = F, colClasses = c(rep("character",4),"numeric", "character", "character")) 
panel.dk<-trimspaces(panel.dk)
panel.gk = read.table("data/toothpa_PANEL_GR_1427_1478.DAT", sep="", header = TRUE, na.strings="", stringsAsFactors = F, colClasses = c(rep("character",4),"numeric", "character", "character"))
panel.gk<-trimspaces(panel.gk)
panel.mk = read.table("data/toothpa_PANEL_MA_1427_1478.DAT", sep="", header = TRUE, na.strings="", stringsAsFactors = F, colClasses = c(rep("character",4),"numeric", "character", "character"))
panel.mk<-trimspaces(panel.mk)

panel.all<-rbind(panel.dk, panel.gk, panel.mk)
```


```{r}
trans.groc = read.table("data/toothpa_groc_1427_1478", sep="", header = TRUE, na.strings="", stringsAsFactors = F, colClasses = c(rep("character",2),rep("numeric", 6), "character", "numeric", "numeric"))
trans.groc<-combineupc(trans.groc)
trans.groc<-trimspaces(trans.groc)

trans.drug = read.table("data/toothpa_drug_1427_1478", sep="", header = TRUE, na.strings="", stringsAsFactors = F, colClasses = c(rep("character",2),rep("numeric", 6), "character", "numeric", "numeric"))
trans.drug<-combineupc(trans.drug)
trans.drug<-trimspaces(trans.drug)

trans.all<-rbind(trans.groc, trans.drug)
```


```{r}
prod.attr = read.csv("toothpa_prod_attr.csv", header = TRUE)
prod.attr$COLUPC<-paste(sprintf("%02d", prod.attr$SY), prod.attr$GE, sprintf("%05d", prod.attr$VEND), sprintf("%05d", prod.attr$ITEM), sep="")
```


```{r}
joined.one<-merge(x=panel.all, y=trans.all, by=c("COLUPC", "IRI_KEY", "WEEK"))
joined.all<-merge(joined.one, prod.attr, by=c("COLUPC"))
```

```{r}
levels(joined.all$SIZE)[8]<-"REGULAR"

reduced.data<-data.frame(PANID=as.factor(joined.all$PANID), 
                         UNITS=as.double(joined.all$UNITS.x), 
                         OUTLET=as.factor(joined.all$OUTLET), 
                         DOLLARS=as.double(joined.all$DOLLARS.x),
                         WEEK=as.double(joined.all$WEEK),
                         VEND=as.factor(joined.all$VEND.x), 
                         ITEM=as.factor(joined.all$ITEM.x), 
                         FEATURE=as.factor(joined.all$F), 
                         DISPLAY=joined.all$D, 
                         PRICEREDUCTION=joined.all$PR, 
                         VOL_EQ=joined.all$VOL_EQ, 
                         SIZE=joined.all$SIZE,
#                         FLAVOR.SCENT=joined.all$FLAVOR.SCENT, 
#                         FORM=joined.all$FORM, 
#                         PACKAGE=joined.all$PACKAGE, 
                         PRODUCT.TYPE=joined.all$PRODUCT.TYPE 
#                         TYPE.OF.FORMULAT=joined.all$TYPE.OF.FORMULA
                         )

```


```{r}
reduced.data$COUNT<-1

reduced.data<-reduced.data[which(reduced.data$PRODUCT.TYPE == "TOOTHPASTE"),]
reduced.data$PRODUCT.TYPE<-factor(reduced.data$PRODUCT.TYPE)

reduced.data<-reduced.data[which(reduced.data$SIZE == "REGULAR"),]
reduced.data$SIZE<-factor(reduced.data$SIZE)

#get rid of size and product type now
cnames<-colnames(reduced.data)
cols.remove<-c(which(cnames == "SIZE"), which(cnames == "PRODUCT.TYPE"))
reduced.data<-reduced.data[,-cols.remove]

vendor.counts<-aggregate(reduced.data$COUNT, by=list(Brand<-reduced.data$VEND), FUN=sum)
#lets take anything above 40
brands<-as.character(vendor.counts[which(vendor.counts$x > 40),1])
# 
# reduced.data<-reduced.data[which(reduced.data$VEND %in% brands),]
# reduced.data$VEND<-factor(reduced.data$VEND)

```

```{r}
purchases.by.brand.per.household<-aggregate(reduced.data$COUNT, by=list(Brand=reduced.data$VEND, Household=reduced.data$PANID), FUN=sum)
total.purchases.per.household<-aggregate(purchases.by.brand.per.household$x, by=list(Household=purchases.by.brand.per.household$Household), FUN=sum)

purchases.by.brand.per.household$loyalty<-0
for (idx in c(1:nrow(purchases.by.brand.per.household))) {
  house<-purchases.by.brand.per.household[idx,2]
  total<-total.purchases.per.household[which(total.purchases.per.household[,1] == house),2]
  purchases.by.brand.per.household[idx,4]<-purchases.by.brand.per.household$x[idx] / total
}

reduced.data$LOYALTY<-0
for (idx in c(1:nrow(reduced.data))) {
  brand<-reduced.data$VEND[idx]
  house<-reduced.data$PANID[idx]
  loyalty<-purchases.by.brand.per.household[which(purchases.by.brand.per.household$Household == house & purchases.by.brand.per.household$Brand == brand),]$loyalty
  reduced.data$LOYALTY[idx]<-loyalty
}

hist(reduced.data$LOYALTY)
barplot(table(reduced.data$VOL_EQ))

```

```{r}
hist(reduced.data$DISPLAY)

reduce.display<-aggregate(reduced.data$DISPLAY, by=list(VEND=reduced.data$VEND, WEEK=reduced.data$WEEK), FUN=sum)
reduce.display[which(reduce.display$x > 0),3]<-1

hist(reduce.display$x)

reduced.data$DISPLAY<-NA
# now replace all the DISPLAY values in our dataset with the weekly avereage for the vendor
for (idx in c(1:nrow(reduced.data))) {
  brand<-reduced.data$VEND[idx]
  week<-reduced.data$WEEK[idx]
  av.display<-reduce.display[which(reduce.display$WEEK == week & reduce.display$VEND == brand),]$x
  reduced.data$DISPLAY[idx]<-av.display
}

# shows that comparitively not many individual items had a display, but usually at least one item from a particular brand had a display
hist(reduced.data$DISPLAY)


hist(reduced.data$PRICEREDUCTION)

reduce.pr<-aggregate(reduced.data$PRICEREDUCTION, by=list(VEND=reduced.data$VEND, WEEK=reduced.data$WEEK), FUN=sum)
reduce.pr[which(reduce.pr$x > 0),3]<-1

reduced.data$PRICEREDUCTION<-NA
for (idx in c(1:nrow(reduced.data))) {
  brand<-reduced.data$VEND[idx]
  week<-reduced.data$WEEK[idx]
  av.pr<-reduce.display[which(reduce.display$WEEK == week & reduce.display$VEND == brand),]$x
  reduced.data$PRICEREDUCTION[idx]<-av.pr
}

# same with price reduction
hist(reduced.data$PRICEREDUCTION)
```


```{r}
# PRICE
reduced.data$PRICE_PER_OUNCE<-(reduced.data$DOLLARS/reduced.data$UNITS) / reduced.data$VOL_EQ
tpriceDf <- reduced.data %>% group_by(WEEK, VEND) %>% dplyr::summarise(AVG_RATE = mean(PRICE_PER_OUNCE))

priceDf <- expand.grid(WEEK=c(min(tpriceDf$WEEK) : max(tpriceDf$WEEK)), VEND = brands)

priceDf <- merge(x=priceDf, y=tpriceDf, by=c("WEEK", "VEND"), all.x=TRUE)

priceDf <- priceDf[order(priceDf$VEND, priceDf$WEEK),]

priceDf[which(priceDf$WEEK == 1427 & priceDf$VEND == 24291),3]<-7.92

priceDf <- priceDf %>%
  group_by(VEND) %>% 
  mutate(AVG_RATE = na.locf(AVG_RATE, na.rm = T))


```

```{r}
# DISPLAY
priceDfDisplay <- expand.grid(WEEK=c(min(reduced.data$WEEK) : max(reduced.data$WEEK)), VEND = brands)
disp.data <- unique(reduced.data[,c(5, 6, 9)])
priceDfDisplay <- merge(x=priceDfDisplay, y=disp.data, by=c("WEEK", "VEND"), all.x=TRUE)

priceDfDisplay[which(priceDfDisplay$WEEK == 1427 & priceDfDisplay$VEND == 24291),3]<-0

priceDfDisplay[which(priceDfDisplay$VEND == 24291),]

priceDfDisplay <- priceDfDisplay %>%
  group_by(VEND) %>% 
  mutate(DISPLAY = na.locf(DISPLAY, na.rm = T))

priceDfDisplay[which(priceDfDisplay$VEND == 24291),]

```

```{r}
# PRICEREDUCTION
priceDfPR <- expand.grid(WEEK=c(min(reduced.data$WEEK) : max(reduced.data$WEEK)), VEND = brands)
pr.data <- unique(reduced.data[,c(5, 6, 10)])
priceDfPR <- merge(x=priceDfPR, y=pr.data, by=c("WEEK", "VEND"), all.x=TRUE)

priceDfPR[which(priceDfPR$WEEK == 1427 & priceDfPR$VEND == 24291),3]<-0

priceDfPR[which(priceDfPR$VEND == 24291),]

priceDfPR <- priceDfPR %>%
  group_by(VEND) %>% 
  mutate(PRICEREDUCTION = na.locf(PRICEREDUCTION, na.rm = T))

priceDfPR[which(priceDfPR$VEND == 24291),]


```


```{r}
combined<-merge(x=merge(x=priceDf, y=priceDfDisplay, by=c("WEEK", "VEND"), all.x=TRUE), y=priceDfPR, by=c("WEEK", "VEND"), all.x=TRUE)
```

```{r}

panelist.attrs = read.csv("data/DEMOS_1322_1373.csv", header = TRUE)
names(panelist.attrs)[1]<-"PANID"
reduced.data.test<-merge(reduced.data, panelist.attrs, by=c("PANID"))

panelist.attrs$MALE_SMOKE[which(panelist.attrs$MALE_SMOKE == ".")]<-0
panelist.attrs$FEM_SMOKE[which(panelist.attrs$FEM_SMOKE == ".")]<-0
panelist.attrs$MALE_SMOKE <- as.numeric(as.character(panelist.attrs$MALE_SMOKE))
panelist.attrs$FEM_SMOKE <- as.numeric(as.character(panelist.attrs$FEM_SMOKE))

attrs.reduced<-panelist.attrs[,c(1, 3, 15, 20)]
panelists<-reduced.data[,c(1, 5)]
panelists.with.income<-merge(x=panelists, y=attrs.reduced, by=c("PANID"), all.x = TRUE)

data.subset<-reduced.data[,c(1, 6, 13)]
panelists.from.trans<-unique(data.subset$PANID)
panelists.with.income<-panelists.with.income[which(panelists.with.income$PANID %in% panelists.from.trans),]

getLoyaltyByPanelistVendor <- function(vendor, panelist){
  return (data.subset[data.subset$VEND == vendor &
                                        data.subset$PANID == panelist,]$LOYALTY[1])
}


for(i in brands){
  param <- paste("loyalty", i, sep="_")
  panelists.with.income[,param] <- sapply(1:nrow(panelists.with.income), function(x) {getLoyaltyByPanelistVendor(vendor = i, panelist = panelists.with.income[x,]$PANID)})
}

test<-panelists.with.income
test[is.na(test)]<-0

```

```{r}

for(level in brands){
  reduced.data[paste("brand", level, sep = "_")] <- ifelse(reduced.data$VEND == level, 1, 0)
}

brand.dummies.data<-reduced.data[,c(1, 5, 14:20)]
test$WEEK<-as.factor(test$WEEK)
test$PANID<-as.factor(test$PANID)

brand.dummies.data$WEEK<-as.factor(brand.dummies.data$WEEK)
brand.dummies.data$PANID<-as.factor(brand.dummies.data$PANID)

all.data.combined<-merge(x=brand.dummies.data, y=test, by=c("PANID", "WEEK"), all.x=TRUE)

all.data.combined
```

```{r}

getVendParamByWeek <- function(vendor, week, param, value){
  param <- 
  return(combined[combined$VEND == vendor &
                  combined$WEEK == week,param][1])
}

for(i in brands){
  avgRateParam <- paste("brand", i, "AVG_RATE", sep="_")
  displayParam <- paste("brand", i, "DISPLAY", sep="_")
  pricereductionParam <- paste("brand", i, "PRICEREDUCTION", sep="_")
  all.data.combined[,avgRateParam] <- sapply(1:nrow(all.data.combined), function(x) { getVendParamByWeek(vendor = i, week = all.data.combined[x,]$WEEK, param = "AVG_RATE")})
  all.data.combined[,displayParam] <- sapply(1:nrow(all.data.combined), function(x) { getVendParamByWeek(vendor = i, week = all.data.combined[x,]$WEEK, param = "DISPLAY")})
  all.data.combined[,pricereductionParam] <- sapply(1:nrow(all.data.combined), function(x) { getVendParamByWeek(vendor = i, week = all.data.combined[x,]$WEEK, param = "PRICEREDUCTION")})
}
  

all.data.combined$PRICE_PER_OUNCE <- NULL

all.data.combined$choice <- paste(all.data.combined$brand_10158, all.data.combined$brand_33200, all.data.combined$brand_35000, all.data.combined$brand_37000, all.data.combined$brand_53100, all.data.combined$brand_77326, sep="")

all.data.combined[all.data.combined$choice == "000000",]$choice <- 0
all.data.combined[all.data.combined$choice == "100000",]$choice <- 1
all.data.combined[all.data.combined$choice == "010000",]$choice <- 2
all.data.combined[all.data.combined$choice == "001000",]$choice <- 3
all.data.combined[all.data.combined$choice == "000100",]$choice <- 4
all.data.combined[all.data.combined$choice == "000010",]$choice <- 5
all.data.combined[all.data.combined$choice == "000001",]$choice <- 6

all.data.combined$choice <- as.numeric(all.data.combined$choice)
write.csv(all.data.combined, file="finaldata.csv")


finaldata <- unique(all.data.combined)

finaldata$WEEK <- as.numeric(as.character(finaldata$WEEK))


mnlmodel <- gam(list(choice~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + WEEK + loyalty_10158 + brand_10158_AVG_RATE +  brand_10158_DISPLAY +  brand_10158_PRICEREDUCTION,  ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + WEEK +  loyalty_33200 + brand_33200_AVG_RATE + brand_33200_DISPLAY + brand_33200_PRICEREDUCTION, ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + WEEK + loyalty_35000 + brand_35000_AVG_RATE + brand_35000_DISPLAY + brand_35000_PRICEREDUCTION, ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + WEEK + loyalty_37000 + brand_37000_AVG_RATE + brand_37000_DISPLAY + brand_37000_PRICEREDUCTION, ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + WEEK + loyalty_53100 + brand_53100_AVG_RATE + brand_53100_DISPLAY + brand_53100_PRICEREDUCTION, ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE +  WEEK + loyalty_77326 + brand_77326_AVG_RATE + brand_77326_DISPLAY + brand_77326_PRICEREDUCTION), data=finaldata, family=multinom(K=6))

gamWeekmodel <- gam(list(choice~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE  + s(WEEK) + loyalty_10158 + brand_10158_AVG_RATE +  brand_10158_DISPLAY +  brand_10158_PRICEREDUCTION,  ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + s(WEEK) +  loyalty_33200 + brand_33200_AVG_RATE + brand_33200_DISPLAY + brand_33200_PRICEREDUCTION, ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + s(WEEK) + loyalty_35000 + brand_35000_AVG_RATE + brand_35000_DISPLAY + brand_35000_PRICEREDUCTION, ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + s(WEEK) + loyalty_37000 + brand_37000_AVG_RATE + brand_37000_DISPLAY + brand_37000_PRICEREDUCTION, ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + s(WEEK) + loyalty_53100 + brand_53100_AVG_RATE + brand_53100_DISPLAY + brand_53100_PRICEREDUCTION, ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE +  s(WEEK) + loyalty_77326 + brand_77326_AVG_RATE + brand_77326_DISPLAY + brand_77326_PRICEREDUCTION), data=finaldata, family=multinom(K=6))

gamWeekPricemodel <- gam(list(choice~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE  + s(WEEK) + loyalty_10158 + s(brand_10158_AVG_RATE) +  brand_10158_DISPLAY +  brand_10158_PRICEREDUCTION,  ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + s(WEEK) +  loyalty_33200 + s(brand_33200_AVG_RATE) + brand_33200_DISPLAY + brand_33200_PRICEREDUCTION, ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + s(WEEK) + loyalty_35000 + s(brand_35000_AVG_RATE) + brand_35000_DISPLAY + brand_35000_PRICEREDUCTION, ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + s(WEEK) + loyalty_37000 + s(brand_37000_AVG_RATE) + brand_37000_DISPLAY + brand_37000_PRICEREDUCTION, ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + s(WEEK) + loyalty_53100 + s(brand_53100_AVG_RATE) + brand_53100_DISPLAY + brand_53100_PRICEREDUCTION, ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE +  s(WEEK) + loyalty_77326 + s(brand_77326_AVG_RATE) + brand_77326_DISPLAY + brand_77326_PRICEREDUCTION), data=finaldata, family=multinom(K=6))

gamWeekPriceDisplaymodel <- gam(list(choice~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE  + s(WEEK, loyalty_10158, brand_10158_AVG_RATE, by=brand_10158_DISPLAY) +  s(WEEK, loyalty_10158, brand_10158_AVG_RATE, by= brand_10158_PRICEREDUCTION),  ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + s(WEEK, loyalty_33200, brand_33200_AVG_RATE, by=brand_33200_DISPLAY) + brand_33200_PRICEREDUCTION, ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + s(WEEK, loyalty_35000, brand_35000_AVG_RATE, by=brand_35000_DISPLAY) + s(WEEK, loyalty_35000, brand_35000_AVG_RATE, by=brand_35000_PRICEREDUCTION), ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + s(WEEK, loyalty_37000, brand_37000_AVG_RATE, by=brand_37000_DISPLAY) + s(WEEK, loyalty_37000, brand_37000_AVG_RATE, by=brand_37000_PRICEREDUCTION), ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + s(WEEK, loyalty_53100, brand_53100_AVG_RATE, by=brand_53100_DISPLAY) + s(WEEK, loyalty_53100, brand_53100_AVG_RATE, by=brand_53100_PRICEREDUCTION), ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE +  s(WEEK, loyalty_77326, brand_77326_AVG_RATE, by=brand_77326_DISPLAY) + s(WEEK, loyalty_77326, brand_77326_AVG_RATE, by=brand_77326_PRICEREDUCTION)), data=finaldata, family=multinom(K=6))

gamWeekPriceDisplayLoyaltymodel <- gam(list(choice~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE  + s(WEEK) + loyalty_10158 + s(brand_10158_AVG_RATE, by= brand_10158_DISPLAY) +  s(brand_10158_AVG_RATE, by=brand_10158_PRICEREDUCTION) + ti(loyalty_10158, brand_10158_AVG_RATE, k = 2),  ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + s(WEEK) +  loyalty_33200 + s(brand_33200_AVG_RATE, by=brand_33200_DISPLAY) + s(brand_33200_AVG_RATE, by = brand_33200_PRICEREDUCTION), ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + s(WEEK) + loyalty_35000 + s(brand_35000_AVG_RATE, brand_35000_DISPLAY) + brand_35000_PRICEREDUCTION, ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + s(WEEK) + loyalty_37000 + s(brand_37000_AVG_RATE, brand_37000_DISPLAY) + brand_37000_PRICEREDUCTION, ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE + s(WEEK) + loyalty_53100 + s(brand_53100_AVG_RATE, brand_53100_DISPLAY) + brand_53100_PRICEREDUCTION, ~Combined.Pre.Tax.Income.of.HH + MALE_SMOKE + FEM_SMOKE +  s(WEEK) + loyalty_77326 + s(brand_77326_AVG_RATE, brand_77326_DISPLAY) + brand_77326_PRICEREDUCTION), data=finaldata, family=multinom(K=6))

summary(mnlmodel)
summary(gamWeekmodel)
summary(gamWeekPricemodel)
summary(gamWeekPriceDisplaymodel)
```

