---
title: "new test"
output: html_document
---

```{r}
library(dplyr)
library(plyr)
require(utils)

library(gamair)
data(chicago)

chicago$death

trimspaces <- function(dat) {
  dat$COLUPC<-trimws(dat$COLUPC)
  dat$WEEK<-trimws(dat$WEEK)
  dat$IRI_KEY<-trimws(dat$IRI_KEY)
  return (dat)
}

combineupc <- function(dat) {
  dat$COLUPC<-paste(sprintf("%02d", dat$SY), dat$GE, sprintf("%05d", dat$VEND), sprintf("%05d", dat$ITEM), sep="")
  return (dat)
}

trans.groc = read.table("data/toothpa_groc_1427_1478", sep="", header = TRUE, na.strings="", stringsAsFactors = F, colClasses = c(rep("character",2),rep("numeric", 6), "character", "numeric", "numeric"))
trans.groc<-combineupc(trans.groc)
trans.groc<-trimspaces(trans.groc)

trans.drug = read.table("data/toothpa_drug_1427_1478", sep="", header = TRUE, na.strings="", stringsAsFactors = F, colClasses = c(rep("character",2),rep("numeric", 6), "character", "numeric", "numeric"))
trans.drug<-combineupc(trans.drug)
trans.drug<-trimspaces(trans.drug)

trans.all<-rbind(trans.groc, trans.drug)

tpriceDf <- group_by(trans.all, WEEK, VEND)
tpriceDf2 <- summarize(tpriceDf, AVG_RATE = mean(DOLLARS/UNITS))
#tpriceDf <- tpriceDf[tpriceDf$VEND %in% prod.attr[prod.attr$PRODUCT.TYPE == 'TOOTHPASTE',]$VEND,]

priceDf <- expand.grid(WEEK=c(min(tpriceDf$WEEK) : max(tpriceDf$WEEK)), VEND = unique(tpriceDf$VEND))
priceDf

priceDf2 <- merge(x=priceDf, y=tpriceDf, by=c("WEEK", "VEND"), all.x=TRUE)
priceDf2
impute.mean <- function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))
imputedPrice <- ddply(priceDf, ~ VEND, transform, AVG_RATE = impute.mean(AVG_RATE))

```



```{r}
# we need to deal with price, first get unit price
reduced.data$UNIT_PRICE<-reduced.data$DOLLARS / reduced.data$UNITS
hist(reduced.data$UNIT_PRICE)
# now get price per ounce
reduced.data$PPO<-reduced.data$UNIT_PRICE / reduced.data$VOL_EQ
hist(reduced.data$PPO)

weekly.av.ppo<-aggregate(reduced.data$PPO, by=list(VEND=reduced.data$VEND, WEEK=reduced.data$WEEK), FUN=mean)
weekly.av.ppo
for (idx in c(1:nrow(reduced.data))) {
  brand<-reduced.data$VEND[idx]
  week<-reduced.data$WEEK[idx]
  av.ppo<-weekly.av.ppo[which(weekly.av.ppo$WEEK == week & weekly.av.ppo$VEND == brand),]$x
  reduced.data$PPO[idx]<-av.ppo
}

reduced.data


# first we need to values for PricePerOunce, Display, PriceReduc, and Loyalty for each vendor for each week
# then for each Panelist for each weeek we need to list every vendor (with PPO, D, PR and L) with only one of those having a TRUE for CHOICE

```
